name: Cache CVE Database

on:
  workflow_dispatch:
  schedule:
    - cron: '12 6 * * *'

env:
  CACHE_KEY: cve-database
  CACHE_REF: refs/heads/main
  CACHE_PATH: ~/.m2/repository/org/owasp/dependency-check-data

jobs:
  create-cache:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CACHE_REF }}

      - name: Restore Existing Cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_PATH }}

      - name: Update CVE Database
        run: mvn org.owasp:dependency-check-maven:update-only -DnvdMaxRetryCount=10 -DnvdApiDelay=15000 -DconnectionTimeout=60000

      - name: Delete Existing Caches
        run: |
          CACHE_IDS=$(gh cache list --key "${{ env.CACHE_KEY }}" --ref "${{ env.CACHE_REF }}" --json id | jq -r '.[] | .id')
          for CACHE_ID in $CACHE_IDS; do
              echo "Deleting cache with ID: $CACHE_ID"
              gh cache delete "${CACHE_ID}"
          done
        env:
          GH_TOKEN: ${{ secrets.DTM_ADMIN }}

      - name: Create Cache
        uses: actions/cache/save@v4
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_PATH }}
